### PR TITLE
Make featured radios on /about random

### LINKED ISSUE #33: Verify channel.slug when editing
When creating a new radio we verify the `slug` to avoid duplicates and suffix a random string, if necessary.

On `channel.edit` we have similar logic but here it is currently broken. We should refactor and reuse the code from `channel.new` somehow.

### LINKED ISSUE #219: Too many radios on /about
On https://radio4000.com/about we load some example radios but at the moment there are way too many.

### PR DESCRIPTION
**Pull request by oskarrough**
By reusing the model hook from our homepage.

Fixes #219

### CODE REVIEW

File: app/about/intro/route.js [hunk 1]
```diff
@@ -1,16 +1,6 @@
 import Ember from 'ember'
+import Route from 'radio4000/channels/index/route'
```
Comment (u8887) [inline app/about/intro/route.js]: A detail, but Ember uses for its adapters/serializers the pattern `ApplicationAdapter`.

Why not continue with this as it also make obvious what this route is, `ChannelsRoute`, and not just a `Route`?

Comment (oskarrough) [reply app/about/intro/route.js]: agree, ty!
